version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  registro-usuario:
    build: ./registro-usuario
    container_name: registro-usuario
    ports:
      - "3001:3001"
    depends_on:
      - redis
    networks:
      - backend

  notificaciones:
    build: ./notificaciones
    container_name: notificaciones
    depends_on:
      - redis
    networks:
      - backend
    
  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    depends_on:
      - registro-usuario
    networks:
      - backend


networks:
  backend:


